spring.data.mongodb.uri=mongodb+srv://pedrorocha:fhvBd0jKw6lXqtRI@livraria-cluster.n6zw4.mongodb.net/biblioteca?retryWrites=true&w=majority


spring.data.mongodb.connection-timeout=30000
spring.data.mongodb.socket-timeout=30000